# Generated by Django 3.0.8 on 2020-07-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('First Service', 'First Service'), ('Second Service', 'Second Service'), ('Third Service', 'Third Service'), ('Youngsters Service', 'Youngsters Service'), ('Midweek Service', 'Midweek Service')], max_length=20)),
                ('date', models.DateField()),
                ('seat_capacity', models.PositiveIntegerField()),
            ],
        ),
    ]
