# Generated by Django 3.0.8 on 2020-07-20 09:35

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200720_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateField(default=datetime.date(2020, 7, 20)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
