# Generated by Django 3.0.8 on 2020-07-20 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200720_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
    ]
