# Generated by Django 3.0.8 on 2020-07-22 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200721_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2020, 7, 22)),
            preserve_default=False,
        ),
    ]
