# Generated by Django 3.0.8 on 2020-07-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendance_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
    ]
