# Generated by Django 3.0.8 on 2020-07-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_attendance_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phone_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
