# Generated by Django 3.0.8 on 2020-07-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='seat_capacity',
        ),
        migrations.AddField(
            model_name='service',
            name='seats',
            field=models.ManyToManyField(to='core.Seat'),
        ),
    ]
