# Generated by Django 3.0.8 on 2020-07-23 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200723_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 23, 12, 30, 40, 844161)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='end',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='start',
            field=models.IntegerField(),
        ),
    ]
